version: '3'
services:
  app:
    build:
      context: ./docker/php
    volumes:
      - .:/ct_cafe_app_server

  web:
    image: nginx:1.17.1-alpine
    ports:
      - "9000:80"
    volumes:
      - .:/ct_cafe_app_server
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
